name: Collector packaging
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout collector-base
        uses: actions/checkout@v4
        with:
          repository: Combodo/itop-data-collector-base
          ref: 1.3.0
          sparse-checkout: |
            conf
            core
            data
            toolkit
          path: ${{ github.repository }}
      - name: Checkout current collector
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}/collectors
      - name: Create package
        uses: thedoctor0/zip-release@0.7.1
        with:
          filename: ../${{ github.repository }}-${{ github.ref_name }}.zip
          path: '*'
          directory: ${{ github.repository_owner }}
          exclusions: '*.git* */composer.json */exclude.txt */Jenkinsfile'
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ github.repository }}-${{ github.ref_name }}.zip
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          updateOnlyUnreleased: true
          token: ${{ secrets.ACCESS_TOKEN }}
